version: '3.8'
services:
  server:
    build: stat-service/server
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow

  client:
    build: stat-service/client
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8081
      - TZ=Europe/Moscow

  main-service:
    build: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STAT_SERVER_URL=http://client:9090
      - TZ=Europe/Moscow

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db:
    image: postgres:13.7-alpine
    container_name: postgres-main-db
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root