version: '3.8'
services:
  server:
    build: stat-service/server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  client:
    build: stat-service/client
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:9090

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root