version: '3.8'
services:
  stats-server:
    build: stat-service/client
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8081

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: stat-service/server
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root